In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA as sklearnPCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.datasets.samples_generator import make_blobs
from sklearn import preprocessing
%matplotlib inline

In [2]:
temp1 = pd.read_csv('All_providers.csv')
temp2 = pd.read_csv('holdingcompany_level_boardband_blocks.csv')

In [3]:
temp2.columns

Index(['HoldingCompanyName', 'dec2014_v3', 'dec2015_v4', 'dec2016_v2',
       'dec2017_v2', 'jun2015_v4', 'jun2016_v3', 'jun2017_v2', 'jun2018_v1',
       'BoardbandBlocks'],
      dtype='object')

In [4]:
data = pd.merge(temp1,temp2, on = ['HoldingCompanyName', 'dec2014_v3', 'dec2015_v4', 'dec2016_v2',
       'dec2017_v2', 'jun2015_v4', 'jun2016_v3', 'jun2017_v2', 'jun2018_v1'], how = 'outer')

In [7]:
data_2014_12=data[data.dec2014_v3==1]
data_2015_6=data[data.jun2015_v4==1]
data_2015_12=data[data.dec2015_v4==1]
data_2016_6=data[data.jun2016_v3==1]
data_2016_12=data[data.dec2016_v2==1]
data_2017_6=data[data.jun2017_v2==1]
data_2017_12=data[data.dec2017_v2==1]
data_2018_6=data[data.jun2018_v1==1]

In [9]:
data_2015=pd.merge(data_2014_12,data_2015_6, on = 'HoldingCompanyName', how = 'outer')
data_2015 = data_2015.fillna(0)
data_2015['avgaddown'] = data_2015.avgaddown_y - data_2015.avgaddown_x
data_2015['avgadup'] = data_2015.avgadup_y - data_2015.avgadup_x
data_2015['consumer'] = data_2015.consumer_y -data_2015.consumer_x
data_2015['states'] = data_2015.states_y - data_2015.states_x
data_2015['BoardbandBlocks'] = data_2015.BoardbandBlocks_y - data_2015.BoardbandBlocks_x
data_2015 = data_2015[['HoldingCompanyName','avgaddown','avgadup','consumer','states','BoardbandBlocks']]
model_data_2015 = data_2015[['avgaddown','avgadup','consumer','states','BoardbandBlocks']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2015)
Kmean = KMeans(n_clusters=3)
Kmean.fit(scaled_data)
data_2015['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 1.96962454e-03,  1.03799338e-03,  5.96497940e-04,
        -1.95293428e-04, -1.31328159e-04],
       [ 8.17040507e-01,  6.45779249e-01,  7.64167598e-04,
         1.32653061e-02,  7.95652377e-03],
       [-8.02696358e-01, -5.93259024e-01, -1.49718163e-03,
        -5.21541950e-02, -1.17226174e-02]])

In [10]:
data_2015_second_half=pd.merge(data_2015_6,data_2015_12, on = 'HoldingCompanyName', how = 'outer')
data_2015_second_half = data_2015_second_half.fillna(0)
data_2015_second_half['avgaddown'] = data_2015_second_half.avgaddown_y - data_2015_second_half.avgaddown_x
data_2015_second_half['avgadup'] = data_2015_second_half.avgadup_y - data_2015_second_half.avgadup_x
data_2015_second_half['consumer'] = data_2015_second_half.consumer_y -data_2015_second_half.consumer_x
data_2015_second_half['states'] = data_2015_second_half.states_y - data_2015_second_half.states_x
data_2015_second_half['BoardbandBlocks'] = data_2015_second_half.BoardbandBlocks_y - data_2015_second_half.BoardbandBlocks_x
data_2015_second_half = data_2015_second_half[['HoldingCompanyName','avgaddown','avgadup','consumer','states','BoardbandBlocks']]
model_data_2015_second_half = data_2015_second_half[['avgaddown','avgadup','consumer','states','BoardbandBlocks']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2015_second_half)
Kmean = KMeans(n_clusters=3)
Kmean.fit(scaled_data)
data_2015_second_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 7.11781699e-03,  3.54188417e-03, -4.76230827e-05,
         4.05317769e-04,  2.27802319e-03],
       [ 7.28334186e-01,  5.77316770e-01,  1.54175558e-03,
         6.74019608e-03,  1.50156990e-02],
       [-9.63712999e-01, -7.48331493e-01, -1.81172964e-03,
        -1.62037037e-02, -1.71759220e-02]])

In [13]:
data_2016_first_half=pd.merge(data_2015_12,data_2016_6, on = 'HoldingCompanyName', how = 'outer')
data_2016_first_half = data_2016_first_half.fillna(0)
data_2016_first_half['avgaddown'] = data_2016_first_half.avgaddown_y - data_2016_first_half.avgaddown_x
data_2016_first_half['avgadup'] = data_2016_first_half.avgadup_y - data_2016_first_half.avgadup_x
data_2016_first_half['consumer'] = data_2016_first_half.consumer_y -data_2016_first_half.consumer_x
data_2016_first_half['states'] = data_2016_first_half.states_y - data_2016_first_half.states_x
data_2016_first_half['BoardbandBlocks'] = data_2016_first_half.BoardbandBlocks_y - data_2016_first_half.BoardbandBlocks_x
data_2016_first_half = data_2016_first_half[['HoldingCompanyName','avgaddown','avgadup','consumer','states','BoardbandBlocks']]
model_data_2016_first_half = data_2016_first_half[['avgaddown','avgadup','consumer','states','BoardbandBlocks']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2016_first_half)
Kmean = KMeans(n_clusters=3)
Kmean.fit(scaled_data)
data_2016_first_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 6.68723155e-03,  2.90351213e-03,  4.78251865e-04,
         9.12013157e-04,  4.90917674e-04],
       [ 8.33455029e-01,  7.44923633e-01,  1.50708980e-03,
         2.55102041e-02,  1.59964892e-03],
       [-8.61293794e-01, -5.91406512e-01, -3.34589938e-03,
        -2.85714286e-02, -2.98957550e-03]])

In [14]:
data_2016_second_half=pd.merge(data_2016_6,data_2016_12, on = 'HoldingCompanyName', how = 'outer')
data_2016_second_half = data_2016_second_half.fillna(0)
data_2016_second_half['avgaddown'] = data_2016_second_half.avgaddown_y - data_2016_second_half.avgaddown_x
data_2016_second_half['avgadup'] = data_2016_second_half.avgadup_y - data_2016_second_half.avgadup_x
data_2016_second_half['consumer'] = data_2016_second_half.consumer_y -data_2016_second_half.consumer_x
data_2016_second_half['states'] = data_2016_second_half.states_y - data_2016_second_half.states_x
data_2016_second_half['BoardbandBlocks'] = data_2016_second_half.BoardbandBlocks_y - data_2016_second_half.BoardbandBlocks_x
data_2016_second_half = data_2016_second_half[['HoldingCompanyName','avgaddown','avgadup','consumer','states','BoardbandBlocks']]
model_data_2016_second_half = data_2016_second_half[['avgaddown','avgadup','consumer','states','BoardbandBlocks']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2016_second_half)
Kmean = KMeans(n_clusters=3)
Kmean.fit(scaled_data)
data_2016_second_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 7.19074810e-03,  3.76701275e-03,  2.72538729e-04,
         5.24356353e-05,  9.51079824e-04],
       [ 7.53477834e-01,  6.06532188e-01,  3.14845100e-03,
         2.22222222e-02,  3.99482744e-03],
       [-6.91280182e-01, -5.04509127e-01, -1.49043214e-02,
        -3.73563218e-02, -1.77145099e-02]])

In [15]:
data_2017_first_half=pd.merge(data_2016_12,data_2017_6, on = 'HoldingCompanyName', how = 'outer')
data_2017_first_half = data_2017_first_half.fillna(0)
data_2017_first_half['avgaddown'] = data_2017_first_half.avgaddown_y - data_2017_first_half.avgaddown_x
data_2017_first_half['avgadup'] = data_2017_first_half.avgadup_y - data_2017_first_half.avgadup_x
data_2017_first_half['consumer'] = data_2017_first_half.consumer_y -data_2017_first_half.consumer_x
data_2017_first_half['states'] = data_2017_first_half.states_y - data_2017_first_half.states_x
data_2017_first_half['BoardbandBlocks'] = data_2017_first_half.BoardbandBlocks_y - data_2017_first_half.BoardbandBlocks_x
data_2017_first_half = data_2017_first_half[['HoldingCompanyName','avgaddown','avgadup','consumer','states','BoardbandBlocks']]
model_data_2017_first_half = data_2017_first_half[['avgaddown','avgadup','consumer','states','BoardbandBlocks']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2017_first_half)
Kmean = KMeans(n_clusters=3)
Kmean.fit(scaled_data)
data_2017_first_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 4.60874968e-03,  2.70296708e-03,  7.44431713e-04,
         1.74256506e-03,  7.60864769e-04],
       [ 7.84529510e-01,  6.27179677e-01,  1.80137441e-03,
         3.53773585e-02,  6.39442274e-03],
       [-8.25833384e-01, -7.29847631e-01, -1.85910596e-03,
        -3.85802469e-02, -6.43728342e-03]])

In [16]:
data_2017_second_half=pd.merge(data_2017_6,data_2017_12, on = 'HoldingCompanyName', how = 'outer')
data_2017_second_half = data_2017_second_half.fillna(0)
data_2017_second_half['avgaddown'] = data_2017_second_half.avgaddown_y - data_2017_second_half.avgaddown_x
data_2017_second_half['avgadup'] = data_2017_second_half.avgadup_y - data_2017_second_half.avgadup_x
data_2017_second_half['consumer'] = data_2017_second_half.consumer_y -data_2017_second_half.consumer_x
data_2017_second_half['states'] = data_2017_second_half.states_y - data_2017_second_half.states_x
data_2017_second_half['BoardbandBlocks'] = data_2017_second_half.BoardbandBlocks_y - data_2017_second_half.BoardbandBlocks_x
data_2017_second_half = data_2017_second_half[['HoldingCompanyName','avgaddown','avgadup','consumer','states','BoardbandBlocks']]
model_data_2017_second_half = data_2017_second_half[['avgaddown','avgadup','consumer','states','BoardbandBlocks']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2017_second_half)
Kmean = KMeans(n_clusters=3)
Kmean.fit(scaled_data)
data_2017_second_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 8.22481261e-03,  5.08736879e-03,  7.24654221e-04,
         4.10913872e-04,  1.45256032e-03],
       [ 8.33886741e-01,  6.73496085e-01,  3.06703728e-03,
         1.87500000e-02,  5.12269620e-03],
       [-7.57302830e-01, -6.42288658e-01, -6.28979734e-02,
        -5.55555556e-02, -6.25391312e-02]])

In [21]:
data_2018_first_half=pd.merge(data_2017_12,data_2018_6, on = 'HoldingCompanyName', how = 'outer')
data_2018_first_half = data_2018_first_half.fillna(0)
data_2018_first_half['avgaddown'] = data_2018_first_half.avgaddown_y - data_2018_first_half.avgaddown_x
data_2018_first_half['avgadup'] = data_2018_first_half.avgadup_y - data_2018_first_half.avgadup_x
data_2018_first_half['consumer'] = data_2018_first_half.consumer_y -data_2018_first_half.consumer_x
data_2018_first_half['states'] = data_2018_first_half.states_y - data_2018_first_half.states_x
data_2018_first_half['BoardbandBlocks'] = data_2018_first_half.BoardbandBlocks_y - data_2018_first_half.BoardbandBlocks_x
data_2018_first_half = data_2018_first_half[['HoldingCompanyName','avgaddown','avgadup','consumer','states','BoardbandBlocks']]
model_data_2018_first_half = data_2018_first_half[['avgaddown','avgadup','consumer','states','BoardbandBlocks']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2018_first_half)
Kmean = KMeans(n_clusters=3)
Kmean.fit(scaled_data)
data_2018_first_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 5.68010116e-03,  3.86509700e-03, -1.02451295e-03,
        -4.78468900e-04,  6.08222058e-04],
       [ 7.59917812e-01,  7.29894732e-01,  9.81821411e-03,
         4.33403805e-02,  3.37207698e-02],
       [-8.53228257e-01, -6.65633135e-01, -6.29037098e-03,
        -4.75206612e-02, -1.64968760e-02]])

In [22]:
data_2015_first_half_group = data_2015[['HoldingCompanyName','group']]
data_2015_second_half_group = data_2015_second_half[['HoldingCompanyName','group']]
data_2016_first_half_group = data_2016_first_half[['HoldingCompanyName','group']]
data_2016_second_half_group = data_2016_second_half[['HoldingCompanyName','group']]
data_2017_first_half_group = data_2017_first_half[['HoldingCompanyName','group']]
data_2017_second_half_group = data_2017_second_half[['HoldingCompanyName','group']]
data_2018_first_half_group = data_2018_first_half[['HoldingCompanyName','group']]

data_total = pd.merge(data_2015_first_half_group,data_2015_second_half_group, on = 'HoldingCompanyName', how = 'outer')
data_total=data_total[['HoldingCompanyName','group_x','group_y']]
data_total=data_total.rename(columns={"group_x": "2015_first_half", "group_y": "2015_second_half"})
data_total = pd.merge(data_total,data_2016_first_half_group, on = 'HoldingCompanyName', how = 'outer')
data_total=data_total.rename(columns={"group": "2016_first_half"})
data_total = pd.merge(data_total,data_2016_second_half_group, on = 'HoldingCompanyName', how = 'outer')
data_total=data_total.rename(columns={"group": "2016_second_half"})
data_total = pd.merge(data_total,data_2017_first_half_group, on = 'HoldingCompanyName', how = 'outer')
data_total=data_total.rename(columns={"group": "2017_first_half"})
data_total = pd.merge(data_total,data_2017_second_half_group, on = 'HoldingCompanyName', how = 'outer')
data_total=data_total.rename(columns={"group": "2017_second_half"})
data_total = pd.merge(data_total,data_2018_first_half_group, on = 'HoldingCompanyName', how = 'outer')
data_total=data_total.rename(columns={"group": "2018_first_half"})

In [23]:
data_total

HoldingCompanyName  2015_first_half  \
0                                            101Netlink              0.0   
1                                                  1958              0.0   
2                                      2Geton Net, Inc.              0.0   
3                  3 Rivers Telephone Cooperative, Inc.              0.0   
4                            3 Rooms Communications LLC              0.0   
5                               360 Communications, LLC              0.0   
6                                            4 SIWI LLC              0.0   
7                                   @Link Services, LLC              0.0   
8                          A Better Wireless, NISP, LLC              0.0   
9                                     ABG Wireless, LLC              0.0   
10                                        ABRY Partners              0.0   
11             Absaraka Cooperative Telephone Co., Inc.              0.0   
12                                            Accelplus              0.0   
13                        Access Cable Television, Inc.              0.0   
14                       Accipiter Communications, Inc.              0.0   
15                            Ace Telephone Association              0.0   
16                            Acme Communications, Inc.              0.0   
17           Acquistions Cogecco Cable Holdings II Inc.              0.0   
18                          Action Communications, Inc.              0.0   
19                          Adak Eagle Enterprises, LLC              0.0   
20                                      Adams CATV Inc.              0.0   
21                         Adams Telephone Co-Operative              0.0   
22                                    ADT Systems, Inc.              0.0   
23                           Aeneas Communications, LLC              0.0   
24                                       Aerowire, Inc.              0.0   
25                            AFES Network Services LLC              0.0   
26                                    Ag Prospects, LLC              0.0   
27       Agate Mutual Telephone Cooperative Association              0.0   
28                     Agri-Valley Communications, Inc.              0.0   
29                                   Air Advantage, LLC              0.0   
...                                                 ...              ...   
3054                                  TCC Networks Inc.              NaN   
3055                           Technically Awesome, LLC              NaN   
3056                                            TEcInfo              NaN   
3057                            TeleGuam Holdings, Inc.              NaN   
3058                               TexaNet Partners LLC              NaN   
3059                             The Peoples State Bank              NaN   
3060                       Tuttle Development Authority              NaN   
3061                                   Unggoy Broadband              NaN   
3062                        Union City Energy Authority              NaN   
3063                      United Datacom Networks, Inc.              NaN   
3064                                      UpNet WI, LLC              NaN   
3065                             Varcomm Holdings, Inc.              NaN   
3066                                           Veopoint              NaN   
3067                              Verde Valley Internet              NaN   
3068                                VGI Technology, Inc              NaN   
3069                                          Vistabeam              NaN   
3070                                W S Electronics LLC              NaN   
3071                                        Warp2, Inc.              NaN   
3072                     West Alabama TV Cable Co, Inc.              NaN   
3073  West Kentucky Rural Telephone Cooperative Corp...              NaN   
3074                 West River Telecommunications Coop              NaN   
3075     

In [24]:
data_total.to_csv('data_group_new.csv',index=False)