In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA as sklearnPCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.datasets.samples_generator import make_blobs
from sklearn import preprocessing
%matplotlib inline

In [32]:
temp1 = pd.read_csv('nst-est2018-alldata.csv')
temp2 = pd.read_csv('state_reference.csv')

In [33]:
temp3 = pd.merge(temp1,temp2, on = 'NAME', how = 'outer')

In [61]:
temp4 = temp3[['StateAbbr','NPOPCHG_2014','NPOPCHG_2015','NPOPCHG_2016','NPOPCHG_2017','NPOPCHG_2018']]
temp4 = temp4.iloc[5:-1,:]
temp4.shape

(51, 6)

In [2]:
data = pd.read_csv('states.csv')
data.columns

Index(['StateAbbr', 'avgaddown', 'avgadup', 'consumer', 'dec2014_v3',
       'dec2015_v4', 'dec2016_v2', 'dec2017_v2', 'jun2015_v4', 'jun2016_v3',
       'jun2017_v2', 'jun2018_v1', 'maxaddown', 'maxadup', 'BoardbandBlocks',
       'HoldingCompanyName'],
      dtype='object')

In [3]:
data_2014_12=data[data.dec2014_v3==1]
data_2015_6=data[data.jun2015_v4==1]
data_2015_12=data[data.dec2015_v4==1]
data_2016_6=data[data.jun2016_v3==1]
data_2016_12=data[data.dec2016_v2==1]
data_2017_6=data[data.jun2017_v2==1]
data_2017_12=data[data.dec2017_v2==1]
data_2018_6=data[data.jun2018_v1==1]

In [96]:
data_2015=pd.merge(data_2014_12,data_2015_6, on = 'StateAbbr', how = 'outer')
data_2015 = data_2015.fillna(0)
data_2015 = pd.merge(data_2015,temp4, on = 'StateAbbr', how = 'inner')
data_2015['avgaddown'] = data_2015.avgaddown_y - data_2015.avgaddown_x
data_2015['avgadup'] = data_2015.avgadup_y - data_2015.avgadup_x
data_2015['consumer'] = data_2015.consumer_y -data_2015.consumer_x
data_2015['HoldingCompanyName'] = data_2015.HoldingCompanyName_y - data_2015.HoldingCompanyName_x
data_2015['BoardbandBlocks'] = data_2015.BoardbandBlocks_y - data_2015.BoardbandBlocks_x
data_2015['population'] = data_2015.NPOPCHG_2015
data_2015 = data_2015[['StateAbbr','avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
model_data_2015 = data_2015[['avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2015)
Kmean = KMeans(n_clusters=2)
Kmean.fit(scaled_data)
data_2015['group']=Kmean.labels_
Kmean.cluster_centers_

array([[-0.04819679, -0.09598877,  0.13222033, -0.27731092,  0.00888202,
         0.0868011 ],
       [ 0.13047172,  0.10930413,  0.09890885,  0.33613445,  0.01067378,
         0.09834341]])

In [97]:
data_2015_second_half=pd.merge(data_2015_6,data_2015_12, on = 'StateAbbr', how = 'outer')
data_2015_second_half = data_2015_second_half.fillna(0)
data_2015_second_half = pd.merge(data_2015_second_half,temp4, on = 'StateAbbr', how = 'inner')
data_2015_second_half['avgaddown'] = data_2015_second_half.avgaddown_y - data_2015_second_half.avgaddown_x
data_2015_second_half['avgadup'] = data_2015_second_half.avgadup_y - data_2015_second_half.avgadup_x
data_2015_second_half['consumer'] = data_2015_second_half.consumer_y -data_2015_second_half.consumer_x
data_2015_second_half['HoldingCompanyName'] = data_2015_second_half.HoldingCompanyName_y - data_2015_second_half.HoldingCompanyName_x
data_2015_second_half['BoardbandBlocks'] = data_2015_second_half.BoardbandBlocks_y - data_2015_second_half.BoardbandBlocks_x
data_2015_second_half['population'] = data_2015_second_half.NPOPCHG_2015
data_2015_second_half = data_2015_second_half[['StateAbbr','avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
model_data_2015_second_half = data_2015_second_half[['avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2015_second_half)
Kmean = KMeans(n_clusters=2)
Kmean.fit(scaled_data)
data_2015_second_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 0.17206134,  0.07668669, -0.0393994 , -0.31818182,  0.08526081,
         0.0582198 ],
       [ 0.13227923,  0.07151871,  0.02178891,  0.56896552,  0.1033419 ,
         0.11524965]])

In [101]:
data_2016_first_half=pd.merge(data_2015_12,data_2016_6, on = 'StateAbbr', how = 'outer')
data_2016_first_half = data_2016_first_half.fillna(0)
data_2016_first_half = pd.merge(data_2016_first_half,temp4, on = 'StateAbbr', how = 'inner')
data_2016_first_half['avgaddown'] = data_2016_first_half.avgaddown_y - data_2016_first_half.avgaddown_x
data_2016_first_half['avgadup'] = data_2016_first_half.avgadup_y - data_2016_first_half.avgadup_x
data_2016_first_half['consumer'] = data_2016_first_half.consumer_y -data_2016_first_half.consumer_x
data_2016_first_half['HoldingCompanyName'] = data_2016_first_half.HoldingCompanyName_y - data_2016_first_half.HoldingCompanyName_x
data_2016_first_half['BoardbandBlocks'] = data_2016_first_half.BoardbandBlocks_y - data_2016_first_half.BoardbandBlocks_x
data_2016_first_half['population'] = data_2016_first_half.NPOPCHG_2016
data_2016_first_half = data_2016_first_half[['StateAbbr','avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
model_data_2016_first_half = data_2016_first_half[['avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2016_first_half)
Kmean = KMeans(n_clusters=2)
Kmean.fit(scaled_data)
data_2016_first_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 0.14073789,  0.09347041,  0.05502472, -0.05555556,  0.04811532,
         0.06015768],
       [ 0.35893815,  0.27886614,  0.16406142,  0.61111111,  0.20233614,
         0.14761574]])

In [102]:
data_2016_second_half=pd.merge(data_2016_6,data_2016_12, on = 'StateAbbr', how = 'outer')
data_2016_second_half = data_2016_second_half.fillna(0)
data_2016_second_half = pd.merge(data_2016_second_half,temp4, on = 'StateAbbr', how = 'inner')
data_2016_second_half['avgaddown'] = data_2016_second_half.avgaddown_y - data_2016_second_half.avgaddown_x
data_2016_second_half['avgadup'] = data_2016_second_half.avgadup_y - data_2016_second_half.avgadup_x
data_2016_second_half['consumer'] = data_2016_second_half.consumer_y -data_2016_second_half.consumer_x
data_2016_second_half['HoldingCompanyName'] = data_2016_second_half.HoldingCompanyName_y - data_2016_second_half.HoldingCompanyName_x
data_2016_second_half['BoardbandBlocks'] = data_2016_second_half.BoardbandBlocks_y - data_2016_second_half.BoardbandBlocks_x
data_2016_second_half['population'] = data_2016_second_half.NPOPCHG_2016
data_2016_second_half = data_2016_second_half[['StateAbbr','avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
model_data_2016_second_half = data_2016_second_half[['avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2016_second_half)
Kmean = KMeans(n_clusters=2)
Kmean.fit(scaled_data)
data_2016_second_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 0.41317375,  0.28779517,  0.02207366, -0.27555556,  0.18029881,
         0.09742193],
       [ 0.10280028,  0.02504308, -0.00181495,  0.24786325,  0.15539762,
         0.10505718]])

In [103]:
data_2017_first_half=pd.merge(data_2016_12,data_2017_6, on = 'StateAbbr', how = 'outer')
data_2017_first_half = data_2017_first_half.fillna(0)
data_2017_first_half = pd.merge(data_2017_first_half,temp4, on = 'StateAbbr', how = 'inner')
data_2017_first_half['avgaddown'] = data_2017_first_half.avgaddown_y - data_2017_first_half.avgaddown_x
data_2017_first_half['avgadup'] = data_2017_first_half.avgadup_y - data_2017_first_half.avgadup_x
data_2017_first_half['consumer'] = data_2017_first_half.consumer_y -data_2017_first_half.consumer_x
data_2017_first_half['HoldingCompanyName'] = data_2017_first_half.HoldingCompanyName_y - data_2017_first_half.HoldingCompanyName_x
data_2017_first_half['BoardbandBlocks'] = data_2017_first_half.BoardbandBlocks_y - data_2017_first_half.BoardbandBlocks_x
data_2017_first_half['population'] = data_2017_first_half.NPOPCHG_2016
data_2017_first_half = data_2017_first_half[['StateAbbr','avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
model_data_2017_first_half = data_2017_first_half[['avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2017_first_half)
Kmean = KMeans(n_clusters=2)
Kmean.fit(scaled_data)
data_2017_first_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 0.34046696,  0.21090963,  0.08019109,  0.13022113,  0.02850183,
         0.08791355],
       [-0.15801829, -0.19708152,  0.27135109,  0.3961039 ,  0.22801966,
         0.13673098]])

In [106]:
data_2017_second_half=pd.merge(data_2017_6,data_2017_12, on = 'StateAbbr', how = 'outer')
data_2017_second_half = data_2017_second_half.fillna(0)
data_2017_second_half = pd.merge(data_2017_second_half,temp4, on = 'StateAbbr', how = 'inner')
data_2017_second_half['avgaddown'] = data_2017_second_half.avgaddown_y - data_2017_second_half.avgaddown_x
data_2017_second_half['avgadup'] = data_2017_second_half.avgadup_y - data_2017_second_half.avgadup_x
data_2017_second_half['consumer'] = data_2017_second_half.consumer_y -data_2017_second_half.consumer_x
data_2017_second_half['HoldingCompanyName'] = data_2017_second_half.HoldingCompanyName_y - data_2017_second_half.HoldingCompanyName_x
data_2017_second_half['BoardbandBlocks'] = data_2017_second_half.BoardbandBlocks_y - data_2017_second_half.BoardbandBlocks_x
data_2017_second_half['population'] = data_2017_second_half.NPOPCHG_2017
data_2017_second_half = data_2017_second_half[['StateAbbr','avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
model_data_2017_second_half = data_2017_second_half[['avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2017_second_half)
Kmean = KMeans(n_clusters=2)
Kmean.fit(scaled_data)
data_2017_second_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 0.30887148,  0.18290584, -0.01235221, -0.16666667,  0.05158241,
         0.06411145],
       [ 0.13100657,  0.09068898,  0.05840487,  0.34920635,  0.24247203,
         0.16500672]])

In [107]:
data_2018_first_half=pd.merge(data_2017_12,data_2018_6, on = 'StateAbbr', how = 'outer')
data_2018_first_half = data_2018_first_half.fillna(0)
data_2018_first_half = pd.merge(data_2018_first_half,temp4, on = 'StateAbbr', how = 'inner')
data_2018_first_half['avgaddown'] = data_2018_first_half.avgaddown_y - data_2018_first_half.avgaddown_x
data_2018_first_half['avgadup'] = data_2018_first_half.avgadup_y - data_2018_first_half.avgadup_x
data_2018_first_half['consumer'] = data_2018_first_half.consumer_y -data_2018_first_half.consumer_x
data_2018_first_half['HoldingCompanyName'] = data_2018_first_half.HoldingCompanyName_y - data_2018_first_half.HoldingCompanyName_x
data_2018_first_half['BoardbandBlocks'] = data_2018_first_half.BoardbandBlocks_y - data_2018_first_half.BoardbandBlocks_x
data_2018_first_half['population'] = data_2018_first_half.NPOPCHG_2018
data_2018_first_half = data_2018_first_half[['StateAbbr','avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
model_data_2018_first_half = data_2018_first_half[['avgaddown','avgadup','consumer','HoldingCompanyName','BoardbandBlocks','population']]
scaled_data = preprocessing.MaxAbsScaler().fit_transform(model_data_2018_first_half)
Kmean = KMeans(n_clusters=2)
Kmean.fit(scaled_data)
data_2018_first_half['group']=Kmean.labels_
Kmean.cluster_centers_

array([[ 0.27840786,  0.12963106, -0.080268  , -0.17816092, -0.00076361,
         0.04025672],
       [-0.01034401, -0.06020678, -0.05504865,  0.21969697,  0.12006519,
         0.18915439]])

In [108]:
data_2015_first_half_group = data_2015[['StateAbbr','group']]
data_2015_second_half_group = data_2015_second_half[['StateAbbr','group']]
data_2016_first_half_group = data_2016_first_half[['StateAbbr','group']]
data_2016_second_half_group = data_2016_second_half[['StateAbbr','group']]
data_2017_first_half_group = data_2017_first_half[['StateAbbr','group']]
data_2017_second_half_group = data_2017_second_half[['StateAbbr','group']]
data_2018_first_half_group = data_2018_first_half[['StateAbbr','group']]

data_total = pd.merge(data_2015_first_half_group,data_2015_second_half_group, on = 'StateAbbr', how = 'outer')
data_total=data_total[['StateAbbr','group_x','group_y']]
data_total=data_total.rename(columns={"group_x": "2015_first_half", "group_y": "2015_second_half"})
data_total = pd.merge(data_total,data_2016_first_half_group, on = 'StateAbbr', how = 'outer')
data_total=data_total.rename(columns={"group": "2016_first_half"})
data_total = pd.merge(data_total,data_2016_second_half_group, on = 'StateAbbr', how = 'outer')
data_total=data_total.rename(columns={"group": "2016_second_half"})
data_total = pd.merge(data_total,data_2017_first_half_group, on = 'StateAbbr', how = 'outer')
data_total=data_total.rename(columns={"group": "2017_first_half"})
data_total = pd.merge(data_total,data_2017_second_half_group, on = 'StateAbbr', how = 'outer')
data_total=data_total.rename(columns={"group": "2017_second_half"})
data_total = pd.merge(data_total,data_2018_first_half_group, on = 'StateAbbr', how = 'outer')
data_total=data_total.rename(columns={"group": "2018_first_half"})

In [109]:
data_total.to_csv('data_group_new_state_level.csv',index=False)